export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children, users, notifications,login
}: {
    children: React.ReactNode,
    users: React.ReactNode,
    notifications: React.ReactNode,
    login: React.ReactNode
}) {
    let isLoggedIn = false
    return isLoggedIn ? (
        <div>
            <div style={{ width: '50%', height: '50px', border: '2px solid black', margin: '10px', background: '#f7d2f2' }}>{children}</div>
            <div style={{ display: "flex" }}>
                <div style={{ width: '200px', height: '300px', border: '2px solid black', margin: '10px', background: 'lightgreen' }}>{users}</div>
                <div style={{ width: '200px', height: '300px', border: '2px solid black', margin: '10px', background: 'lightgreen' }}>{notifications}</div>
            </div>
        </div>
    ) : (login)
}
